openapi: 3.0.0
info:
  title: books
  version: '1.0'
  description: ''
servers:
  - url: 'https://localhost:8080/api/v1'
paths:
  /books:
    get:
      summary: 本を検索する
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  books:
                    anyOf:
                      - type: array
                        items: {}
                      - $ref: ./models/books.v1.yaml
    parameters: []
  '/books/{isbn}':
    parameters:
      - type: string
        name: isbn
        in: path
        required: true
        schema:
          type: string
        description: ''
    put:
      summary: 本を登録する
      responses:
        '501':
          description: Not Implemented
      description: ''
    delete:
      summary: ''
      responses:
        '501':
          description: Not Implemented
  '/books/{isbn}/actions':
    parameters:
      - type: string
        name: isbn
        in: path
        required: true
    post:
      summary: 本に対する行動
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/bookaction.v1.yaml
            examples:
              本を借りる:
                value:
                  type: borrow
                  userId: '1234567'
              本を返す:
                value:
                  type: return
                  userId: '1234567'
        description: パラメータのISBNの
      description: ''
      parameters: []
components:
  schemas: {}
