openapi: 3.0.0
info:
  title: books
  version: '1.0'
  description: ''
servers:
  - url: 'https://localhost:8080/api/v1'
paths:
  /books:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
    parameters: []
  '/books/{isbn}':
    parameters:
      - type: string
        name: isbn
        in: path
        required: true
        schema:
          type: string
        description: ''
    put:
      summary: ''
      responses:
        '501':
          description: Not Implemented
      description: ''
    delete:
      summary: ''
      responses:
        '501':
          description: Not Implemented
  '/books/{isbn}/actions':
    parameters:
      - type: string
        name: isbn
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
    post:
      summary: ''
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                userId:
                  type: string
            examples:
              借りる:
                value:
                  type: borrow
                  userId: '1234567'
        description: ''
components:
  schemas: {}
