openapi: 3.0.0
info:
  title: books
  version: 1.0.0
  description: ''
servers:
  - url: 'http://localhost:8080/api/v1'
tags:
  - name: books
    description: ""
  - name: lendingRecords
    description: ""
  - name: users
    description: ""
  - name: openBd
paths:
  /books:
    $ref: './paths/books.yaml#/books'
  '/books/{isbn}':
    $ref: './paths/books.yaml#/isbn'
  /books-by-actions:
    $ref: './paths/books.yaml#/actions'
